skip_local_validator = true

[toolchain]
anchor_version = "1.2.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
deposit_lock = "FX2jWasLMqeG3X4ntc8jogMgxRdbMMSxKcfTWJxexQbY"

[programs.localnet]
deposit_lock = "FX2jWasLMqeG3X4ntc8jogMgxRdbMMSxKcfTWJxexQbY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
